Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
nota1, nota2, media : real

Inicio
// Seção de Comandos
escreval ("Digite nota1 aqui: ")
leia (nota1)
escreval ("Digite nota2 aqui: ")
leia (nota2)
média <- (nota1 + nota2)/2
escreval ("Sua média é ", media)
se media >=7 entao
escreval ("Aprovado")
leia (média)
Fimalgoritmo