Algoritmo "Repetição Nome"
//
//
// Descrição   : Exercício de repetição
// Autor(a)    : Guilherme
// Data atual  : 10/08/2020
Var
   // Seção de Declarações das variáveis
   nome: inteiro

Inicio
   // Seção de Comandos
   escreval ("Sistema de repetição pré-definido")
   escreval ("_______________________________________________________________")
   escreval ()

   timer 3
   enquanto (nome < 1000) faca
      escreval ("Guilherme Mota")
      nome <- nome+1
   fimenquanto

Fimalgoritmo